'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Owner
    Public Property OwnerID As Integer
    Public Property GivenName As String
    Public Property Surname As String
    Public Property Phone As Integer

    Public Overridable Property Pets As ICollection(Of Pet) = New HashSet(Of Pet)

End Class
