'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pet
    Public Property PetName As String
    Public Property Type As String
    Public Property OwnerID As Integer

    Public Overridable Property Owner As Owner
    Public Overridable Property Treatments As ICollection(Of Treatment) = New HashSet(Of Treatment)

End Class
